/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package labsemana9juniornunez;

import javax.swing.JOptionPane;

/**
 *
 * @author Junior Nuñes
 */
public class MenuPrincipal extends javax.swing.JDialog {
private JTunes jtunes = new JTunes(5);
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        agregarcancion = new javax.swing.JButton();
        buscarcancion = new javax.swing.JButton();
        ratesong = new javax.swing.JButton();
        printsongs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("BIENVENIDO A iTUNES");

        jLabel2.setText("Que desea hacer?");

        agregarcancion.setText("Agregar Cancion");
        agregarcancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarcancionActionPerformed(evt);
            }
        });

        buscarcancion.setText("Buscar Cancion");
        buscarcancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarcancionActionPerformed(evt);
            }
        });

        ratesong.setText("Rate Song");
        ratesong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratesongActionPerformed(evt);
            }
        });

        printsongs.setText("Print Songs");
        printsongs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printsongsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(printsongs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ratesong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarcancion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agregarcancion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregarcancion)
                .addGap(29, 29, 29)
                .addComponent(buscarcancion)
                .addGap(30, 30, 30)
                .addComponent(ratesong)
                .addGap(27, 27, 27)
                .addComponent(printsongs)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarcancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarcancionActionPerformed
        try {
            int codigo = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese el codigo de la cancion:"));
            
            String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre de la cancion:");
            
            double precio = Double.parseDouble(JOptionPane.showInputDialog(this, "Ingrese el precio de la cancion:"));

            if (jtunes.addSong(codigo, nombre, precio)) {
                JOptionPane.showMessageDialog(this, "Cancion añadida exitosamente.");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo añadir la cancion. El codigo ya existe o no hay espacio.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en la entrada de datos.");
        }
    }//GEN-LAST:event_agregarcancionActionPerformed

    private void buscarcancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarcancionActionPerformed
        try {
            int codigo = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese el codigo de la cancion a buscar:"));
            Song song = jtunes.searchSong(codigo);
            if (song != null) {
                JOptionPane.showMessageDialog(this, "Cancion encontrada: " + song.toString());
            } else {
                JOptionPane.showMessageDialog(this, "No se encontro una cancion con ese codigo.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en la entrada de datos.");
        }
    }//GEN-LAST:event_buscarcancionActionPerformed

    private void ratesongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratesongActionPerformed
         try {
            int codigo = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese el código de la cancion a calificar:"));
            int estrellas = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la cantidad de estrellas (0-5):"));
            if (jtunes.rateSong(codigo, estrellas)) {
                JOptionPane.showMessageDialog(this, "Cancion calificada exitosamente.");
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró la cancion o las estrellas no son validas.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en la entrada de datos.");
        }
    }//GEN-LAST:event_ratesongActionPerformed

    private void printsongsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printsongsActionPerformed
         String canciones = jtunes.printSongs();
        if (!canciones.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Canciones almacenadas:\n" + canciones);
        } else {
            JOptionPane.showMessageDialog(this, "No hay canciones almacenadas.");
        }
    }//GEN-LAST:event_printsongsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuPrincipal dialog = new MenuPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarcancion;
    private javax.swing.JButton buscarcancion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton printsongs;
    private javax.swing.JButton ratesong;
    // End of variables declaration//GEN-END:variables
}
